name: Hadolint
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
  pull_request:
    branches: [main]
    paths:
      - 'Dockerfile'

jobs:
  hadolint:
    runs-on: ubuntu-latest
    name: Hadolint-your-PR
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
