name: Hadolint
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
  pull_request:
    branches: [main]
    paths:
      - 'Dockerfile'

jobs:
  hadolint:
    runs-on: ubuntu-latest
    name: Hadolint-your-PR
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: hadolint/hadolint-action@3fc49fb50d59c6ab7917a2e4195dba633e515b29 # v3.2.0
